version: "3"

services:

  postgres:
    extends:
      file: ./Backend/docker-compose.yaml
      service: postgres
    networks:
      project-network:
        ipv4_address: 192.168.41.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  backend:
    extends:
      file: ./Backend/docker-compose.yaml
      service: backend
    networks:
      project-network:
        ipv4_address: 192.168.41.2
    depends_on:
      - postgres
  
  frontend:
    extends:
      file: ./Frontend/docker-compose.yaml
      service: frontend
    networks:
      project-network:
        ipv4_address: 192.168.41.3

networks:
  project-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.41.0/24
