name: Backend Run Event

on:
  repository_dispatch:
    types: [backend-run]

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Git SubModule Update
        run: git submodule update --remote Backend

      - name: Docker Compose
        run: docker-compose up --build -d