name: Stack Deployment

on:
  push:
    branches:
      - feat_deployment

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            postgres
            backend
            frontend