name: Stack Deployment

on:
  push:
    branches:
      - feat_deployment
  pull_request:
    branches:
      -feat_deployment

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: List Backend directory contents
        run: ls -al /home/runner/work/stack/Backend/

      - name: Docker Compose
        run: docker-compose up --build -d