name: Stack Run

on:
  push:
    branches:
      - feat_deployment
  pull_request:
    branches:
      - feat_deployment

jobs:
  run-container:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Git SubModule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive

      - name: Docker Compose
        run: |
          POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
          POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
          docker compose up --build -d